version: '3'
services:
    credit-card-transaction-services:
        build:
            dockerfile: ./Dockerfile
            context: .
        image: leoslassis/credit-card-transaction-services
        container_name: credit-card-transaction-services
        ports:
            - '8082:8082'
        networks:
            - production-network
        links:
            - mongodb
        depends_on:
            - mongodb
            - rabbitmq
    rabbitmq:
        image: 'rabbitmq:3-management'
        container_name: rabbitmq
        ports:
            - '15672:15672'
            - '5672:5672'
        networks:
            - production-network
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
          - 27017:27017
        networks:
            - production-network
networks:
    production-network:
        driver: bridge
